name: noise_protocol
version: 0.2.0
homepage: https://github.com/dint-dev/cryptography
description:
  A Dart implementation of Noise protocol, which can be used for securing communications (E2EE,
  etc.).

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  cryptography: ^2.0.0
  meta: ^1.3.0
  typed_data: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.0

dependency_overrides:
  cryptography:
    path: '../cryptography'