name: noise_protocol
version: 0.2.0-nullsafety.0
homepage: https://github.com/dint-dev/cryptography
description:
  A Dart implementation of Noise protocol, which can be used for securing communications (E2EE,
  etc.).

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.5
  cryptography: ^2.0.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6
  typed_data: ^1.3.0-nullsafety.5

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13

dependency_overrides:
  crypto: 3.0.0-nullsafety.0
  cryptography:
    path: '../cryptography'