name: cryptography
version: 0.2.2
homepage: https://github.com/dint-dev/cryptography
description:
  Cryptography for applications. Key exchange (X25519, ECDH-P256, etc.), encryption (AES, Chacha20),
  and cryptographic hash functions (Blake2s, SHA2). Web Crypto API support.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: ^1.14.0
  crypto: ^2.1.0
  js: ^0.6.0
  meta: ^1.1.0
  typed_data: ^1.1.0

dev_dependencies:
  benchmark_harness: ^1.0.0
  pedantic: ^1.8.0
  test: ^1.6.0
