name: kms_flutter
version: 0.2.0-nullsafety.0
homepage: https://github.com/dint-dev/cryptography
description:
  Key Management Service for Flutter applications. Supports Keystore (Android), Keychain (iOS / Mac
  OS X), and browsers.

environment:environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  collection: ^1.15.0-nullsafety.5
  cryptography: ^2.0.0-nullsafety.2
  flutter:
    sdk: flutter
  kms: ^0.5.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13

dependency_overrides:
  crypto: ^3.0.0-nullsafety.0
  cryptography:
    path: '../cryptography'
  kms:
    path: '../kms'