name: kms_flutter
version: 0.2.0
homepage: https://github.com/dint-dev/cryptography
description:
  Key Management Service for Flutter applications. Supports Keystore (Android), Keychain (iOS / Mac
  OS X), and browsers.

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  collection: ^1.15.0
  cryptography: ^2.0.0
  flutter:
    sdk: flutter
  kms: ^0.5.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.0

dependency_overrides:
  cryptography:
    path: '../cryptography'
  kms:
    path: '../kms'