name: jwk
version: 0.2.2
homepage: https://github.com/dint-dev/cryptography
description: JWK (JSON Web Key) encoding and decoding (for package:cryptography).

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  cryptography: ^2.4.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.19.0

dependency_overrides:
  cryptography:
    path: ../cryptography