name: jwk
version: 0.2.3
homepage: https://github.com/dint-dev/cryptography
description: JWK (JSON Web Key) encoding and decoding (for package:cryptography).

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  cryptography: ^2.5.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.19.0

dependency_overrides:
  cryptography:
    path: ../cryptography