name: example
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  kms_flutter:
    path: ../

dev_dependencies:
  integration_test: ^1.0.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

dependency_overrides:
  cryptography:
    path: '../../cryptography'
  kms:
    path: '../../kms'