name: example
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kms_flutter:
    path: ../

dev_dependencies:
  e2e: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

dependency_overrides:
  cryptography:
    path: '../../cryptography'
  kms:
    path: '../../kms'