name: kms_adapter_cupertino
version: 0.1.0
homepage: https://github.com/dint-dev/cryptography
description: An adapter for 'package:kms' that exposes Keychain in iOS / Mac OS X.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cupertino_ffi: ^0.2.1
  cryptography: ^0.2.6
  kms: ^0.1.0
  meta: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

dependency_overrides:
  cryptography:
    path: '../cryptography'
  kms:
    path: '../kms'