name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  cryptography_flutter:
    path: ../
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.2
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

dependency_overrides:
  crypto: ^3.0.0
  cryptography:
    path: ../../cryptography