name: cryptography_flutter
description:
  Makes 'package:cryptography' use platform APIs in Android, iOS, and Mac OS X. The package can
  make performance up to 100 times better.
version: 2.1.1
homepage: https://github.com/dint-dev/cryptography

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  cryptography: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  cryptography:
    path: ../cryptography

flutter:
  plugin:
    platforms:
      android:
        package: dev.dint.cryptography_flutter
        pluginClass: CryptographyFlutterPlugin
      ios:
        pluginClass: CryptographyFlutterPlugin
      macos:
        pluginClass: CryptographyFlutterPlugin
