name: cryptography
version: 2.0.0-nullsafety.1
homepage: https://github.com/dint-dev/cryptography
description:
  Cryptographic algorithms for encryption, digital signatures, key agreement, authentication, and
  hashing. AES, Chacha20, ED25519, X25519, and more. Web Crypto support.

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.5
  crypto: ^3.0.0-nullsafety.0
  fixnum: ^1.0.0-nullsafety.0
  js: ^0.6.3-nullsafety.3
  meta: ^1.3.0-nullsafety.6
  typed_data: ^1.3.0-nullsafety.5

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13

dependency_overrides:
  crypto: ^3.0.0-nullsafety.0
