name: kms
version: 0.2.0
homepage: https://github.com/dint-dev/cryptography
description: Key Management Service (KMS) API for managing cryptographic keys securely.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cryptography: ^0.2.5
  meta: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

dependency_overrides:
  cryptography:
    path: '../cryptography'