name: kms
version: 0.4.0
homepage: https://github.com/dint-dev/cryptography
description: Key Management Service (KMS) API for managing cryptographic keys securely.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  collection: ^1.10.0
  cryptography: ^0.3.5
  meta: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0

dependency_overrides:
  cryptography:
    path: '../cryptography'