name: kms
version: 0.5.1
homepage: https://github.com/dint-dev/cryptography
description: Key Management Service (KMS) API for managing cryptographic keys securely.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  cryptography: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.0

dependency_overrides:
  cryptography:
    path: ../cryptography