name: cryptography_test
version: 0.1.0
homepage: https://github.com/dint-dev/cryptography
description: A package for testing and benchmarking cryptographic algorithm implementations that
  implement "package:cryptography" interfaces.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  crypto: ^3.0.0

  # Packages by the Google:
  test: ^1.19.0
  typed_data: ^1.3.0

  # Packages by the same maintainers as this package
  # (github.com/dint-dev):
  cryptography: ^2.5.0

dev_dependencies:
  # Packages by the Google:
  lints: ^2.0.1

dependency_overrides:
  cryptography:
    path: ../cryptography