name: cryptography_test
version: 0.1.0
homepage: https://github.com/dint-dev/cryptography
description: A package for testing and benchmarking cryptographic algorithm implementations that
  implement "package:cryptography" interfaces.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cryptography: ^2.2.3
  test: ^1.19.0
  typed_data: ^1.3.0

dev_dependencies:
  lints: ^2.0.1

dependency_overrides:
  cryptography:
    path: ../cryptography