name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies (cryptography)
        working-directory: cryptography
        run: pub get

      - name: Install dependencies (kms)
        working-directory: kms
        run: pub get

      - name: Run tests (cryptography)
        working-directory: cryptography
        run: pub run test --platform=vm

      - name: Run tests (kms)
        working-directory: kms
        run: pub run test --platform=vm