name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:dev

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies (cryptography)
        working-directory: cryptography
        run: dart pub get

      - name: Install dependencies (jwk)
        working-directory: jwk
        run: dart pub get

      - name: Run tests (cryptography)
        working-directory: cryptography
        run: dart test --platform=vm

      - name: Run tests (jwk)
        working-directory: jwk
        run: dart test --platform=vm