name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: ./all.sh pub get
      - name: Run tests
        run: ./all.sh pub run test --platform=vm